
services:
  app:
    image: carapp:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_USERNAME: ${MAVEN_USERNAME}
        MAVEN_PASSWORD: ${MAVEN_PASSWORD}
        MAVEN_URL: ${MAVEN_URL}
        NPM_URL: ${NPM_URL}
    ports:
      - "8080:8080"
    networks:
      - car_app_network
    env_file:
      - .env
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - car_app_network
    env_file:
      - .env

networks:
  car_app_network:
    driver: bridge
volumes:
  db_data:
