
server:
    error:
        include-message: always
spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        driver-class-name: org.postgresql.Driver
        password: local
        platform: postgres
        url: jdbc:postgresql://localhost:5432/carApp
        username: local
    jackson:
        deserialization:
            use_java_array_for_json_array: true
        serialization:
            write-dates-as-timestamps: false
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                    create_namespaces: true
                show_sql: false
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    web:
        resources:
            static-locations: classpath:/static/browser
    security:
        basic:
            enabled: true
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
            resource:
                user-info-uri: https://openidconnect.googleapis.com/v1/userinfo