security:
    basic:
        enabled: false

server:
    error:
        include-message: always
spring:
    security.rememberme.key: 123
    config:
        import: optional:file:.env[.properties]
    datasource:
        driver-class-name: org.postgresql.Driver
        password: local
        platform: postgres
        url: jdbc:postgresql://localhost:5432/testdb
        username: local
    jackson:
        deserialization:
            use_java_array_for_json_array: true
        serialization:
            write-dates-as-timestamps: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        generate-ddl: true
        properties:
            hibernate:
                hbm2ddl:
                    auto: create-drop
                    create_namespaces: true
                show_sql: false
        #                connection:
        #                    url: jdbc:postgresql://localhost:5432/testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS core
        show-sql: false
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
logging:
    level:
        pl.sztyro: DEBUG
        org:
            hibernate: ERROR
            springframework:
                transaction: DEBUG
            orm:
                jpa: ERROR
